
* 使用emacs编程
** tabbar使用
#+begin_tabbar_usage mode

tabbar-backward           (C-c <C-left>)
tabbar-forward            (C-c <C-right>)
tabbar-backward-group     (C-c <C-up>)
tabbar-forward-group      (C-c <C-down>)

tabbar-local-mode         (C-c <C-f10>)

tabbar-press-home         (C-c <C-home>)
tabbar-press-scroll-left  (C-c <C-prior>)
tabbar-press-scroll-right (C-c <C-next>)

#+end_tabbar_usage


** ido-mode使用
#+begin_ido-mode mode
清除 (\c-l)
#+end_ido-mode

** recent-jump使用(recent-jump.el)
   #+begin_recent-jump mode
推荐按键
(global-set-key (kbd "C-o") 'recent-jump-jump-backward)
(global-set-key (kbd "M-o") 'recent-jump-jump-forward)

使用按键
(global-set-key (kbd "<M-S-left>") 'recent-jump-jump-backward)
(global-set-key (kbd "<M-S-right>") 'recent-jump-jump-forward)
   #+end_recent-jump

** ace-jump-mode使用(ace-jump-mode.el)
#+begin_ace-jump mode
 (define-key global-map (kbd "C-c SPC") 'ace-jump-mode)
(define-key viper-vi-global-user-map (kbd "SPC") 'ace-jump-mode)
#+end_ace-jump

** bookmark使用
*** Add a bookmark
Open a file you want to bookmark. Then, Alt+x bookmark-set
【Ctrl+x r m】. It'll add current file to bookmark file.
It will prompt you for a name. Bookmark can be a file or a directory.

*** List Bookmarks
Alt+x list-bookmark 【Ctrl+x r l】 → Open bookmark file.

When in bookmark file, press Enter to open the item under cursor.

*** Open a Bookmark
To open a bookmarked item, Alt+x bookmark-jump 【Ctrl+x r b】, then type a name.

You can type a asterisk * for wildcard. For example, “*today” will match “todo today”.

*** Remove / Rename Bookmark
When in the bookmark file:

Type d to mark the current item for remove.
Type x to remove all D marked ones.
Type r to rename current item's title.
Type s to save the change.


** smart-compile使用(smart-compile.el)

** window-numbering使用(window-numbering.el)

** win-switch使用(win-switch.el)

** psvn使用(psvn.el)

** magit使用(magit.el)

** fci-mode使用(fill-column-indicator.el)

** vimpluse使用(vimpluse.el)

** drag-stuff使用(drag-stuff.el)
#+begin_drag-stuff mode
    (define-key map (kbd "<M-up>") 'drag-stuff-up)
    (define-key map (kbd "<M-down>") 'drag-stuff-down)
    (define-key map (kbd "<M-right>") 'drag-stuff-right)
    (define-key map (kbd "<M-left>") 'drag-stuff-left)
#+end_drag-stuff

** highlights使用(volatile-highlights,highlight-tail,highlight-parentheses,highlight-symbol)
#+begin_highlight mode
  (global-set-key [(meta f3)] 'highlight-symbol-at-point)
  (global-set-key (kbd "ESC <f3>") 'highlight-symbol-at-point) ; putty
  (global-set-key [f3] 'highlight-symbol-next-or-prev)
  (global-set-key [(shift f3)] 'highlight-symbol-prev)
  (global-set-key [f15] 'highlight-symbol-prev) ; S-f3
  ;; (global-set-key (kbd "ESC ESC <f3>") 'highlight-symbol-prev)
  (global-set-key [(control f3)] 'highlight-symbol-query-replace))
#+end_highlight

** mark-multiple使用(mark-multiple.el)

** multi-term使用(multi-term.el)

** dired+使用(dired+.el)

** browse-kill-ring使用

** ifdef使用(ifdef.el,hide-ifdefs,show-ifdefs)
*** Hide-Ifdef 辅助模式

在 C mode 或者 C++ mode 下启用 hide-ifdef-mode 可以帮助我们隐藏那些讨厌
的 #ifdef ... #endif 代码块，使程序更容易阅读。

当我们阅读源代码的时候，尤其是阅读那些历史很悠久的源代码的时候，经常看到
其中插入了很多的条件预处理指令，可移植性越强的程序，条件预处理指令就越多，
这些指令把源文件分割成了很多碎片，阅读时会分散我们的注意力，使我们难于看
清程序的整体结构。

`hide-ifdef-mode' 就是用来对付这样的源代码文件的，如果我们打开这个辅助模
式，就可以把那些条件不成立的代码块隐藏起来，使程序的结构更加清晰。

**** 条件编译指令的作用

条件编译指令经常用来处理可移植性问题，比如对于不同的平台使用不同的代码，
象下面这样：

#ifdef VMS
#include <ssdef.h>
#endif

#ifdef BSD_SYSTEM
#include <sys/ioctl.h>
#endif

#ifdef WINDOWSNT
#include <fcntl.h>
#include <windows.h>
#endif

还可以用条件编译指令建立起公共的 C 和 C++ 头文件：

#ifdef __cplusplus
namespace std {
         extern "C" {
#endif

char* func_1(char*, const char*);
int func_2(const char*);
double func_3(int n);

#ifdef __cplusplus
         }
}
#endif

有时候用 #if 0 ... #endif 来注释掉大块代码：

#if 0
int obsolete_fonc(int n)
{
         return n*n + 1;
}
#endif

这是一种很常用的技巧，在自由软件的源代码中经常出现，采用这种方法进行注释
恢复起来很方便。

使用 `hide-ifdef-mode' 可以把那些条件不成立、被预处理器忽略掉的代码块会自
动隐藏起来，显示成缩略符号(...)，这样代码就会清爽很多，更容易阅读。

**** 常用命令

启用 `hide-ifdef-mode' 的命令是：

`M-x hide-ifdef-mode'

启用了这个辅助模式之后，就可以用下面两个命令隐藏或显示代码块：

M-x hide-ifdefs  (或者 C-c @ h) 隐藏代码
M-x show-ifdefs  (或者 C-c @ s) 显示代码

需要注意的是 Emacs 并不能主动地根据文件中的 `#define ...' 找出哪那些符号
是已定义的，哪些符号是为定义的，因此需要我们用下面两个命令手工定义[1]:

C-c @ d         hide-ifdef-define 定义一个符号
C-c @ u         hide-ifdef-undef  取消符号定义

另外，也可以不管符合是否是有定义的，强制隐藏或显示代码块：

C-c @ C-d       hide-ifdef-block 隐藏一块代码，不论符合是否已定义
C-c @ C-s       show-ifdef-block 显示隐藏的代码，不论符合是否已定义

**** 可以设置的变量

下面几个变量会影响隐藏的方式：

***** `hide-ifdef-lines'
如果这个变量的值为真，那么 #if, #ifdef, #ifndef, #else, 和 #endif 这些预
处理命令本身也会隐藏起来。

也就是说，如果把这个变量的值设置为真：
(setq hide-ifdef-lines t)
那么隐藏的效果是：

#ifdef WINDOWSNT          |    ...
#include <fcntl.h>        |    ...
#include <windows.h>      |
#endif                    |

如果设置为 nil:
(setq hide-ifdef-lines nil)
那么隐藏的效果是：

#ifdef WINDOWSNT          |   #ifdef WINDOWSNT...
#include <fcntl.h>        |   #endif
#include <windows.h>      |
#endif                    |

***** `hide-ifdef-initially'
这个变量决定了刚进入 Hide-Ifdef 辅助模式时，是否立即处于隐藏状态，如果这
个变量的值为 nil，那么进入 Hide-Ifdef 辅助模式以后，需要自己发出
`hide-ifdefs' (C-c @ h) 命令，才隐藏代码。

***** `hide-ifdef-read-only'
如果这个变量的值为 non-nil，那么处于隐藏模式时，buffer会变成只读的，这样
可以避免误删代码。在只读和非只读状态之间切换可以使用这个命令：
`hide-ifdef-toggle-read-only' (C-c @ C-q)

***** `hide-ifdef-env'
这是个关联链表，其中保存着当前 buffer 中已定义的符号。我们可以利用这个变
量为定义那些全局的符号，例如，对于linux平台可以定义 GNU_LINUX，对于 C++
程序可以定义 __cplusplus 等：
(setq hide-ifdef-env '((GNU_LINUX . t)
                        (__GNUC__ . t)
                        (__cplusplus . t)))

***** `hide-ifdef-define-alist'
我们可以事先定义几个链表，每个链表中保存需要定义的符号，例如下面的语句定
义了两个符号链表 list1 和 list2，然后用 hide-ifdef-use-define-alist 选择
使用 list2，使 TWO 和 THREE 成为有定义的符号。
(setq hide-ifdef-define-alist
                 '((list1 ONE TWO)
                   (list2 TWO THREE)))
(hide-ifdef-use-define-alist 'list2) ; use list2 by default
在工作过程中，我们可以 `hide-ifdef-use-define-alist' (C-c @ U) 命令切换，
选择使用自己定义的其它链表，比如 list1。

**** 配置示例
(add-hook 'hide-ifdef-mode-hook
      (lambda ()
          (unless hide-ifdef-define-alist
            (setq hide-ifdef-define-alist
                 '((list1 ONE TWO)
                   (list2 TWO THREE))))
          (hide-ifdef-use-define-alist 'list2))) ; use list2 by default


** doc-mode/doxymacs-mode使用

** cscope使用(xcscope.el)

** xgtags使用(global使用)
#+begin_global mode
http://www.gnu.org/software/global

 (define-key map "\e*" 'xgtags-pop-stack)
 (define-key map "\e." 'xgtags-find-tag)
 (define-key map "\e\t" 'xgtags-complete-tag)

(define-key map 'button3 (when flag 'xgtags-pop-stack))
(define-key map 'button2 (when flag 'xgtags-find-tag-by-event))
or
(define-key map [mouse-3] (when flag 'xgtags-pop-stack))
(define-key map [mouse-2] (when flag 'xgtags-find-tag-by-event))

(define-key keymap "\C-cw" sub-keymap)
(define-key sub-keymap "d" 'xgtags-find-tag)
(define-key sub-keymap "c" 'xgtags-find-rtag)
(define-key sub-keymap "s" 'xgtags-find-symbol)
(define-key sub-keymap "g" 'xgtags-find-with-grep)
(define-key sub-keymap "i" 'xgtags-find-with-idutils)
(define-key sub-keymap "n" 'xgtags-select-next-tag)
(define-key sub-keymap "p" 'xgtags-select-prev-tag)
(define-key sub-keymap "\t" 'xgtags-make-complete-list)
(define-key sub-keymap "u" 'xgtags-pop-stack)
;;   (define-key sub-keymap "" 'xgtags-find-tag-from-here)
(define-key sub-keymap "f" 'xgtags-find-file)
;;   (define-key sub-keymap "" 'xgtags-display-browser)
(define-key sub-keymap "x" 'xgtags-switch-to-buffer)
(define-key sub-keymap "\C-x" 'xgtags-switch-to-buffer-other-window)
(define-key sub-keymap "r" 'xgtags-query-replace-regexp)
#+end_global

** sourcepair使用

** code-import使用

** undo-tree使用

** yasnippet


** auto-complete


** company

** ace-windows插件
 M-p 打开ace-windows插件
可以快速在多个窗口调整
** 使用帮助手册
man命令可以直接查找对应的技术手册
** org-mode
*** 插入源代码
先使用< s tab 会再光标出插入SRC,在使用C-M-i，可以选择插入的语言。
*** org-mode导出
In emacs, Alt+x org-export-dispatch 【Ctrl+c Ctrl+e】 to export. To export to HTML, the key is 【Ctrl+c Ctrl+e h h】

*** org-mode任务管理
TODO Heading

To mark a heading as todo item, start it with “TODO”.
* TODO call mom for bday
* DONE finish coding absca
Place your cursor on a heading, 【Shift+→】 → change heading among 3 states: {TODO, DONE, normal}. It will add the word “TODO” or “DONE” in the heading.
【Ctrl+c Ctrl+v】 → view just todo headings.
Insert Date/Time

【Ctrl+c .】 → insert a date like this: <2010-07-31 Sat>.
【Ctrl+u Ctrl+c .】 → insert datetime, like this: <2012-02-09 Thu 03:32>.
Move cursor into a date, then press 【Shift+↑】 to increase any {year, month, day, hour}. Press 【Shift+↓】 to decrease.
Tags

Each heading may have keywords, called “tags”.

For example: work, family, urgent, coding….

The syntax for tag is any word between colon, like this: :something: or :this:that:. They are usually placed at end of the line. Like this:

* call mom for bday. :family:...
* finish writing the org-mode tutorial. :emacs:work:
Tag name characters must be any alphabets A to Z, a to z, or digits 0 to 9, or _, @.

Tag name cannot have space, nor hyphen -.

Tags are inherited from parent nodes, in the sense that when you search for a tag, a heading with that tag will show but also all its children, even if the children's headings do not contain that tag.

【Ctrl+c Ctrl+q】 → insert a tag. You can also just type the tag yourself.

Show Headings by Tag

【Ctrl+c \】 → show only headings of a given tag.

** magit
http://ergoemacs.org/emacs/emacs_magit-mode_tutorial.html

* emacs常用插件说明
** 基础插件
  插件   用途
  helm/helm-ag
  dracula-theme / molokai-theme          配色
  neotree  文件列表
  super-save   自动保存
  popwin  窗口操作
  window-numbering  窗口跳转

  direx  打开当前文件目录
  crux  打开应用
  undo-tree  撤销
  swiper，counsel  快捷命令
  which-key  快捷键提示
  exec-path-from-shell  加载shell的path定义
  avy, ag, ace-jump-mode  搜索
  iedit  多光标
  ag 快速查找
  [[https://github.com/syohex/emacs-helm-ag]]

  auto-yasnippet
  [[https://github.com/abo-abo/auto-yasnippet]]
*** dired
使用 C-x d 就可以进入Dired Mode，这个模式类似于图形界面系统中的资源管理器。
你可以在其中查看文件和目录的详细信息，对他们进行各种操作，
甚至复制粘贴缓冲区中的内 容。下面是一些常用的操作（下面的所有键均需在 Dired Mode 下使用），
+ 创建目录
g 刷新目录
C 拷贝
D 删除
R 重命名
d 标记删除
u 取消标记
x 执行所有的标记
j k 上下移动光标
h l 返回上级目录、进入目录


*** bm/helm-bm
bm可以设置可视化的bookmark
helm-bm用于查看,定位可视化bm
<C>-f2 当前行设置bookmark
C-c b 显示所有设置的bookmark,并可以输入关键词进行搜索bookmark


** 开发插件
  editorconfig  代码格式
  yasnippet  代码片段
  company，company-ycmd，company-web  智能补全
  dash-at-point / zeal-at-point  代码帮助
  xcscope, ggtags  代码跳转
  flycheck, flycheck-ycmd  代码检查
  magit, git-gutter  git
  smartparens  自动添加匹配括号
  highlight-parentheses  高亮括号
  indent-guide  缩进线
  aggressive-indent  缩进对齐
  expand-region  扩展选择区域
  anaconda-mode, elpy  Python
  go-mode, company-go  go
  markdown-mode  markdown
  js2-mode  javascript
  web-mode, emmet-mode  web

* emacs基础
** 启动elisp的交互命令行
   you can Alt+x ielm. It will start a interactive elisp command line interface.
   
   运行某一段elisp，M-x eval-region
   查找某一个函数：M-x:describe-function 或者使用快捷键C-x h
   
** 列出emacs所有的hook
Alt+x apropos-variable then type “-hook”.
How to find the name of hook?
To find a mode's hook,
Alt+x describe-variable, then try to type a name you guessed, press Tab for completion.
Or
Alt+x apropos-variable
Type “-hook”, press Enter.
Note: A major mode may have more than 1 hook.

** copy to the regiester (非常好用)


Emacs has “registers” that allows you to store arbitrary text. It is like multiple-clipboards.

Let's say you have 2 pieces of text: A and B. You need to paste A in some places, paste B in other places.

Example use:

Select a text, then Alt+x copy-to-register 【Ctrl+x r s】, then type 3. This will store the text in register “3”.
To paste, Alt+x insert-register 【Ctrl+x r i】, then type 3. This will paste text stored in register “3”.
Register name can be any single digit 0 to 9 or single letter a to z.

http://ergoemacs.org/emacs_manual/emacs/Registers.html



* 自定义的按键

** 光标移动
s-m 括号,引号之前的调整

** mark相关的操作
设置全局最大的mark数为16个,文件内部的最大mark数为6个
C-c m  设置mark
<f1>   文件内部的mark跳转
<f2>   全局的mark跳转

** hiligth-tail
   输入的时候，会有渐变效果，输入更有感觉。

** highlight-symbol高亮符号字符串
C-c g d 高亮光标所在的字符串
s-j 查找下一个高亮的位置
s-k 查找上一个高亮
** C-h m查看当前的major mode相关信息
** Cask文件格式
(depends-on "monokai-theme" :git "https://github.com/oneKelvinSmith/monokai-emacs/releases" :ref "02c5f5d")
cask可以指定安装git对应的版本号。
